recipes = {'oil':
                [
                {'name':'wellpads-pipelines',       'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add wellpads -> pipelines'},
                {'name':'oilfields-pipelines',      'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add fields -> pipelines'},
                {'name':'pipelines-pipelines',      'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add pipelines -> pipelines'},
                {'name':'pipelines-pipelines',      'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add pipelines <- pipelines'},
                {'name':'ports-pipelines',          'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add pipelines -> ports'},
                {'name':'ports-pipelines',          'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add pipelines <- ports'},
                {'name':'ports-shipping',           'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add ports -> shipping_lanes'},
                {'name':'ports-shipping',           'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add ports <- shipping_lanes'},
                {'name':'shipping-shipping',        'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add shipping_lanes -> shipping_lanes'},
                {'name':'shipping-shipping',        'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add shipping_lanes <- shipping_lanes'},
                {'name':'refineries-pipelines',     'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add pipelines -> refineries'},
                {'name':'refineries-pipelines',     'reverse':False,    'dup_1':False, 'dup_2':True,    'desc':'add refineries -> pipelines_2'},
                {'name':'ports-pipelines',          'reverse':True,     'dup_1':True,  'dup_2':True,    'desc':'add pipelines_2 -> ports_2 '},
                {'name':'ports-pipelines',          'reverse':False,    'dup_1':True,  'dup_2':True,    'desc':'add pipelines_2 <- ports_2 '},
                {'name':'ports-shipping',           'reverse':False,    'dup_1':True,  'dup_2':True,    'desc':'add ports_2 -> shipping_lanes_2'},
                {'name':'ports-shipping',           'reverse':True,     'dup_1':True,  'dup_2':True,    'desc':'add ports_2 <- shipping_lanes_2'},
                {'name':'pipelines-pipelines',      'reverse':False,    'dup_1':True,  'dup_2':True,    'desc':'add pipelines_2 -> pipelines_2'},
                {'name':'pipelines-pipelines',      'reverse':True,     'dup_1':True,  'dup_2':True,    'desc':'add pipelines_2 <- pipelines_2'},
                {'name':'shipping-shipping',        'reverse':False,    'dup_1':True,  'dup_2':True,    'desc':'add shipping_lanes_2 -> shipping_lanes_2'},
                {'name':'shipping-shipping',        'reverse':True,     'dup_1':True,  'dup_2':True,    'desc':'add shipping_lanes_2 <- shipping_lanes_2'},
                {'name':'pipelines-cities',         'reverse':False,    'dup_1':True,  'dup_2':False,   'desc':'add pipelines_2 -> cities'},
                {'name':'powerstn-pipelines',       'reverse':True,     'dup_1':False, 'dup_2':True,    'desc':'add pipelines_2 -> power_stn'},
                ],
        'gas':
                [
                {'name':'wellpads-pipelines',       'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add wellpads -> pipelines'},
                {'name':'oilfields-pipelines',      'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add fields -> pipelines'},
                {'name':'pipelines-pipelines',      'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add pipelines -> pipelines'},
                {'name':'pipelines-pipelines',      'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add pipelines <- pipelines'},
                {'name':'lng-pipelines',            'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add pipelines -> lng'},
                {'name':'lng-pipelines',            'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add pipelines <- lng'},
                {'name':'lng-shipping',             'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add lng -> shipping_lanes'},
                {'name':'lng-shipping',             'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add lng <- shipping_lanes'},
                {'name':'shipping-shipping',        'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add shipping_lanes -> shipping_lanes'},
                {'name':'shipping-shipping',        'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add shipping_lanes <- shipping_lanes'},
                {'name':'procplant-pipelines',      'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add pipelines -> procplant'},
                {'name':'procplant-pipelines',      'reverse':False,    'dup_1':False, 'dup_2':True,    'desc':'add procplant -> pipelines_2'},
                {'name':'lng-pipelines',            'reverse':True,     'dup_1':True,  'dup_2':True,    'desc':'add pipelines_2 -> lng_2 '},
                {'name':'lng-pipelines',            'reverse':False,    'dup_1':True,  'dup_2':True,    'desc':'add pipelines_2 <- lng_2 '},
                {'name':'lng-shipping',             'reverse':False,    'dup_1':True,  'dup_2':True,    'desc':'add lng_2 -> shipping_lanes_2'},
                {'name':'lng-shipping',             'reverse':True,     'dup_1':True,  'dup_2':True,    'desc':'add lng_2 <- shipping_lanes_2'},
                {'name':'pipelines-pipelines',      'reverse':False,    'dup_1':True,  'dup_2':True,    'desc':'add pipelines_2 -> pipelines_2'},
                {'name':'pipelines-pipelines',      'reverse':True,     'dup_1':True,  'dup_2':True,    'desc':'add pipelines_2 <- pipelines_2'},
                {'name':'shipping-shipping',        'reverse':False,    'dup_1':True,  'dup_2':True,    'desc':'add shipping_lanes_2 -> shipping_lanes_2'},
                {'name':'shipping-shipping',        'reverse':True,     'dup_1':True,  'dup_2':True,    'desc':'add shipping_lanes_2 <- shipping_lanes_2'},
                {'name':'pipelines-cities',         'reverse':False,    'dup_1':True,  'dup_2':False,   'desc':'add pipelines_2 -> cities'},
                {'name':'powerstn-pipelines',       'reverse':True,     'dup_1':False, 'dup_2':True,    'desc':'add pipelines_2 -> power_stn'},
                ],

        'coal':
                [
                {'name':'coalmines-railways',       'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add coalmines -> railways'},
                {'name':'railways-railways',        'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add railways -> railways'},
                {'name':'railways-railways',        'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add railways <- railways'},
                {'name':'ports-railways',           'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add railways -> ports'},
                {'name':'ports-railways',           'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add railways <- ports'},
                {'name':'ports-shipping',           'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add ports -> shipping_lanes'},
                {'name':'ports-shipping',           'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add ports <- shipping_lanes'},
                {'name':'shipping-shipping',        'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add shipping_lanes -> shipping_lanes'},
                {'name':'shipping-shipping',        'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add shipping_lanes <- shipping_lanes'},
                {'name':'powerstn-railways',        'reverse':True,     'dup_1':False, 'dup_2':False,   'desc':'add railways -> powerstn'},
                {'name':'railways-cities',          'reverse':False,    'dup_1':False, 'dup_2':False,   'desc':'add railways -> cities'},
                ]
        }